sudo: false  # Use container-based infrastructure
language: python
python:
- "2.7"
- "3.4"
addons:
  apt:
    packages:
    - python-scipy
    - python3-scipy
virtualenv: # Needed in conjunction with apt-get'ing scipy
  system_site_packages: true
install:
- pip install -r requirements.txt
- python install .  
script: nosetests test && ./lint.sh
deploy:
  provider: pypi
  user: hammerlab
  password: # See http://docs.travis-ci.com/user/encryption-keys/
    secure: gJSWl4PLXKtVc2ERwbzfd4qKk9Yy4T8dpfR7Q89VLVXTd7Tv1SsEknShJZUFaCPN85aYFcAWsoOI6vSlBSdXeTONU/pmPgcWOLfiErsgCqUs6qq7edOhrtOS307SREX4oF6AF2iyJduWAF4NPq+9IoJUROIiB4u5qeUtWfVu2Eo=
  on:
    tags: true