sudo: false  # Use container-based infrastructure
language: minimal
python:
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      # Needed for NetMHC
      - tcsh
cache:
  # cache pip files, also directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries
  directories:
    - $HOME/.cache/pyensembl/
    - $HOME/.cache/pip
before_install:
  # Commands below copied from: http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # install netmhcbundle
  - git clone https://mhcbundle:$MHC_BUNDLE_PASS@github.com/openvax/netmhc-bundle.git
  - export NETMHC_BUNDLE_HOME=$PWD/netmhc-bundle
  - mkdir tmp
  - export NETMHC_BUNDLE_TMPDIR=$PWD/tmp
  - export PATH=$PATH:$NETMHC_BUNDLE_HOME/bin
  # needed for MHCflurry predictor test
  - export KERAS_BACKEND=tensorflow
  # we want to include vaxrank unit tests as a general integration test to make sure the stack
  # isn't broken in an obvious way
  # - git clone https://github.com/openvax/vaxrank.git
env:
  global:
    # MHC_BUNDLE_PASS
    - secure: "HVKAOpCRrP6qdH+XeFKHb7EqDP+Jqa9SrXCE/41Vumho9qzmONiYf3MyM21bDCkRHh/euYmkWPjfXzSPZPPpP492sfD/d7nv3aSXZfGyQzkAoAmIR0qyhWWjREpPQYISjAHx5pq1tOJktR86krbtPWHCkpb+HFYjwBAjJWPtYs8="
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy pandas nose mkl-service pandoc
  - source activate test-environment
  - pip install pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
  # - pip install --upgrade -r $PWD/vaxrank/requirements.txt
before_script:
  # needed for MHCflurry predictor test
  - mhcflurry-downloads fetch
  # needed for vaxrank
  # - pyensembl install --release 87 --species human
  # - pyensembl install --release 87 --species mouse
script:
  - ./lint.sh
  # -a '!skip' lets us skip certain tests on travis (relevant for vaxrank)
  # this command runs both mhctools and vaxrank tests.
  # Sometimes they don't print output for a long time; travis_wait extends the time
  # allowed with no output.
  # TODO: figure out what in the Vaxrank tests (or after) is forcing us to use
  # travis_wait
  - nosetests -sv test --with-coverage --cover-package=mhctools #  -a '!skip' $PWD/vaxrank
after_success:
  coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: openvax
  password: # See http://docs.travis-ci.com/user/encryption-keys/
    secure: "S5hx/6cv1fNKvb5iyXfzGOxOiQYy6CSnqvlKirSEjyDgfFcLlIU7sUBTFiiDIDIUaCtFN0klvmTZ9c7Yxk0c0n3zlXSwLrdqkma25cab8xEY0CHkelAf56WcZfy22AZVPOG+ndCSSsOY31XEZL9smD63gmr7zKIOPEy9fXAJLAw="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
