sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.4"
addons:
  apt:
    packages:
      # Needed for NetMHC
      - tcsh
      # install pandoc for use with pypandoc for converting the README
      # from markdown to RST
      - pandoc
before_install:
  # Commands below copied from: http://conda.pydata.org/docs/travis.html
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # install netmhcbundle
  - git clone https://mhcbundle:$MHC_BUNDLE_PASS@github.com/hammerlab/netmhc-bundle.git
  - export NETMHC_BUNDLE_HOME=$PWD/netmhc-bundle
  - mkdir tmp
  - export NETMHC_BUNDLE_TMPDIR=$PWD/tmp
  - export PATH=$PATH:$NETMHC_BUNDLE_HOME/bin
  # needed for MHCflurry predictor test
  - export KERAS_BACKEND=theano
  # install vaxrank for unit tests
  - git clone https://github.com/hammerlab/vaxrank.git
env:
  global:
    # MHC_BUNDLE_PASS
    - secure: "TIminZrp9m1kMXhemqz8Zx4BjojIoEYZJnNrDrL6T/pKMpP5FQ6sprj8meGfNse4ApRIPmp5lhqxbPOe7Cg7ooetIcORekjRueHwRkYXqgMbgffgZYuEJTAGLKFsBDEXFD1kWT7igmvXFsP1T0bb1TxRPK93Q5G+e1dEAm6Iqwo="
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy scipy nose pandas mkl-service theano
  - source activate test-environment
  - pip install pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
before_script:
  # needed for MHCflurry predictor test
  - mhcflurry-downloads fetch
script:
  - ./lint.sh
  # we want to include vaxrank unit tests as a general integration test to make sure the stack
  # isn't broken in an obvious way
  - pip install --upgrade -r $PWD/vaxrank/requirements.txt
  - pyensembl install --release 87 --species human
  - pyensembl install --release 87 --species mouse
  # this matches the vaxrank repo tests command: certain tests shouldn't run on travis
  # travis_wait lets us avoid failures if no output is seen for 10 minutes, which happens sometimes
  - travis_wait nosetests -sv test --with-coverage --cover-package=mhctools -a '!skip'
after_success:
  coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: hammerlab
  password: # See http://docs.travis-ci.com/user/encryption-keys/
    secure: "hptQUnWnbqfMeiDPWX5Jw34qBHfuDuKofjyeF6m+eofg5XRWr4HsKZraghk7lMLQWcmkpX9FPwMYXHfQA+FO+81ColrPll3BCx7DlG71qGOoNEsbVN8C/OM6z+/+QWXlebxHGu9f06uFJC8glo8gKUSKrtNjJ5GsI+buDyE2a74="
  on:
    branch: master
